### ISSUE TITLE
Weird ring like blur and images

### ISSUE THREAD

**Issue by thanhtmph06914** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#39]
I noticed a weird artifact when shows gradient fills or blurs. This are displayed in a "ring like" manner, and I have also discovered that it is a problem of how the OS shows images in general, because Youtube videos and other images with gradients are also shown weirdly. When I take a screenshot of the problem and try to see it in another computer, it shows it just fine. So I'll post picture of the screen taken with a camera, to exemplify.
Please help me!

This is the blured background of Launchpad:
https://i.redd.it/crq31emx47s11.jpg
https://i.redd.it/9im08q2h57s11.jpg

**Comment by MohammadtaghiFarkhondekar** [comment]
In screen I can't see Gl553vd . It's Look like Lenovo laptop...

**Comment by thanhtmph06914** [comment]
i use similar images, please help me 🥇

**Comment by keinsell** [comment]
@thanhtmph06914 MacOS Launchpod, by default bluring background, it doesn't look like a real issue because that may be caused by low-resolution display, for example on my laptop blur on some wallpapers wasn't good quality but when I connected 2k display it just looks a lot better.

I think that issue can be closed.

**Comment by iSWORD** [comment]
Yeah I can't reproduce this either on my GL553VD. Either provide more details or this should be closed.

**Comment by thanhtmph06914** [comment]
Thanks all!
